apiVersion: v1
kind: Service
metadata:
  name: drupal
  namespace: exercise-01
  labels:
    app: drupal
    tier: frontend
spec:
  type: NodePort
  ports:
    - name: drupal
      port: 80
      targetPort: http
  selector:
    app: drupal
    tier: frontend
