apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: exercise-01
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
spec:
  tls:
  - hosts:
      - myblog.com
    secretName: sslcerts
  rules:
  - host: myblog.com
    http:
      paths:
        - path: /
          backend:
            serviceName: wordpress
            servicePort: http
  - host: drupal.myblog.com
    http:
      paths:
        - path: /
          backend:
            serviceName: drupal
            servicePort: http