kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-pvc
  namespace: exercise-01
  labels:
    app: wordpress
    type: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
